### ISSUE TITLE
dbt Analytics Engineering Certification Study

### ISSUE THREAD

**Issue by rupert160** [rupert160/dbt_demo#1]
IN ORDER TO sit the dbt Analytics exam
AS A examinee
I REQUIRE the completion of items:
https://www.getdbt.com/certifications/analytics-engineer-certification-exam#faq

**Task Groups:**
- [ ]  Developing `dbt` models
- [ ] Understanding `dbt` model governance
- [ ] Debugging data modeling errors
- [ ] Managing data pipelines
- [ ] Implementing `dbt` tests
- [ ] Creating and Mantaining `dbt` documentation
- [ ] Implementing and Maintaining External Dependencies
- [ ] Leveraging the `dbt` state
